# Generated by Django 2.2 on 2019-06-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='海报')),
                ('start_time', models.DateTimeField(verbose_name='举办开始时间')),
                ('end_time', models.DateTimeField(verbose_name='举办结束时间')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('hot', models.IntegerField(verbose_name='热度')),
                ('people_num', models.CharField(max_length=200, verbose_name='活动人数')),
                ('details', models.TextField(verbose_name='活动详情')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='海报')),
                ('start_time', models.DateTimeField(verbose_name='举办开始时间')),
                ('end_time', models.DateTimeField(verbose_name='举办结束时间')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('people_num', models.CharField(max_length=200, verbose_name='活动人数')),
                ('details', models.TextField(verbose_name='活动详情')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '活动临时表',
                'verbose_name_plural': '活动临时表',
                'db_table': 'logactivity',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='类型名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '活动类型',
                'verbose_name_plural': '活动类型',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=200, verbose_name='openid')),
                ('nickname', models.CharField(max_length=200, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('real_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='真实姓名')),
                ('iphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ManyToManyField(blank=True, null=True, related_name='many_activity', to='stage.Activity', verbose_name='关注的活动')),
                ('user_focus', models.ManyToManyField(blank=True, null=True, related_name='many_user', to='stage.User', verbose_name='关注的用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=200, verbose_name='介绍')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_address', models.CharField(max_length=200, verbose_name='活动地址')),
                ('file_path', models.FileField(upload_to='file_path/', verbose_name='视频文件')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('comments_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('ups_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('transpond_num', models.IntegerField(default=0, verbose_name='转发数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.Activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isups', models.IntegerField(default=1, verbose_name='点赞')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'ups',
            },
        ),
        migrations.CreateModel(
            name='TranSpond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '转发',
                'verbose_name_plural': '转发',
                'db_table': 'transpond',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='票种名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('amount', models.IntegerField(verbose_name='张数')),
                ('audit', models.IntegerField(choices=[(0, '无需审核'), (1, '需我审核')], verbose_name='审核')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('explain', models.CharField(blank=True, max_length=200, null=True, verbose_name='票种说明')),
                ('one_buy', models.IntegerField(blank=True, null=True, verbose_name='单次购买')),
                ('less', models.IntegerField(blank=True, null=True, verbose_name='最少购买张数')),
                ('more', models.IntegerField(blank=True, null=True, verbose_name='最多购买张数')),
                ('order_start', models.DateTimeField(verbose_name='购票开始时间')),
                ('order_end', models.DateTimeField(verbose_name='购票结束时间')),
                ('valid_start', models.DateTimeField(verbose_name='有效时间开始')),
                ('valid_end', models.DateTimeField(verbose_name='有效时间结束')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '票种',
                'verbose_name_plural': '票种',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='LogTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='票种名称')),
                ('price', models.CharField(max_length=200, verbose_name='价格')),
                ('amount', models.IntegerField(verbose_name='张数')),
                ('audit', models.IntegerField(choices=[(0, '无需审核'), (1, '需我审核')], verbose_name='审核')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('explain', models.CharField(blank=True, max_length=200, null=True, verbose_name='票种说明')),
                ('one_buy', models.IntegerField(blank=True, null=True, verbose_name='单次购买')),
                ('less', models.IntegerField(blank=True, null=True, verbose_name='最少购买张数')),
                ('more', models.IntegerField(blank=True, null=True, verbose_name='最多购买张数')),
                ('order_start', models.DateTimeField(verbose_name='购票开始时间')),
                ('order_end', models.DateTimeField(verbose_name='购票结束时间')),
                ('valid_start', models.DateTimeField(verbose_name='有效时间开始')),
                ('valid_end', models.DateTimeField(verbose_name='有效时间结束')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.LogActivity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '票种临时表',
                'verbose_name_plural': '票种临时表',
                'db_table': 'logticket',
            },
        ),
        migrations.CreateModel(
            name='LogApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more', models.TextField(default='', verbose_name='更多项')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.LogActivity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '报名表单临时表',
                'verbose_name_plural': '报名表单临时表',
                'db_table': 'logapplyform',
            },
        ),
        migrations.AddField(
            model_name='logactivity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Type', verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_create_user', to='stage.User', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('ups_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('big_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fu_parent', to='stage.Comments', verbose_name='最大评论')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bor_parent', to='stage.Comments', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more', models.TextField(default='', null=True, verbose_name='更多项')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '报名表单',
                'verbose_name_plural': '报名表单',
                'db_table': 'applyfrom',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('phone', models.CharField(max_length=200, verbose_name='手机号')),
                ('email', models.CharField(max_length=200, verbose_name='邮箱')),
                ('more', models.TextField(null=True, verbose_name='更多')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.Activity', verbose_name='活动')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.Ticket', verbose_name='票种')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '报名',
                'verbose_name_plural': '报名',
                'db_table': 'apply',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Type', verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='stage.User', verbose_name='用户'),
        ),
    ]
