# Generated by Django 2.2 on 2019-06-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=200, verbose_name='所属单位'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(default='', verbose_name='介绍'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=200, verbose_name='订单号')),
                ('order_money', models.FloatField(verbose_name='订单金额')),
                ('pay', models.IntegerField(verbose_name='支付方式')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.Activity', verbose_name='活动')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.Ticket', verbose_name='票种')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stage.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
    ]
