# Generated by Django 2.2 on 2019-06-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_auto_20190614_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=200, verbose_name='退款交易号')),
                ('money', models.FloatField(verbose_name='退款金额')),
                ('status', models.IntegerField(choices=[(0, '退款中'), (1, '退款成功'), (2, '退款失败')], verbose_name='退款状态')),
                ('cause', models.TextField(verbose_name='退款原因')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '退款',
                'verbose_name_plural': '退款',
            },
        ),
    ]
